name: nhinh_uit_devera
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assorted_layout_widgets: ^5.0.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
  - family:  Avenir-ExtraBold
    fonts:
    - asset: fonts/AvenirNextRoundedPro-ExtraBold.ttf
  - family:  Avenir-Bold
    fonts:
      - asset: fonts/AvenirNextRoundedPro-Bold.ttf
  - family:  Avenir-Regular
    fonts:
      - asset: fonts/AvenirNextRoundedPro-Regular.ttf

   